import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="header">
            <Link href="../ortos">
            <div className="logo">
              <img src="/logoortos.png" width="50px" height="50px" />
              <div className="logo-text">
                <h2 className="h2header">Ortos</h2>
                <h3>Odontologia Especializada</h3>
              </div>
            </div>
            </Link>
            <div className="menu">
             <Link href="../ortos#procedimentos"> <h5>Procedimentos</h5></Link>
              <Link href="../ortos#localizacao"> <h5>Localizaçâo</h5> </Link>
              <h5>Sobre</h5>
              <h5>Dúvidas</h5>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
